<a href="https://colab.research.google.com/github/varun0852/ML-PROJECTS/blob/main/boston_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from scipy import stats
import warnings
warnings.filterwarnings("ignore")
from statsmodels.stats.stattools import durbin_watson

In [ ]:
# from google.colab import files
# uploaded = files.upload("")

In [ ]:
df = pd.read_csv("Boston (2).csv")

In [ ]:
df.head()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [ ]:
df1 = df.drop("Unnamed: 0" , axis =1)

In [ ]:
df1.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [ ]:
df1.corr()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
crim,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
zn,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
indus,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
chas,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260
nox,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
rm,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360
age,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
dis,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
rad,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
tax,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
ptratio,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
black,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
lstat,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
medv,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000

In [ ]:
x = df1.drop("medv" , axis = 1)
y = df1["medv"]

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  black    506 non-null    float64
 12  lstat    506 non-null    float64
dtypes: float64(10), int64(3)
memory usage: 51.5 KB

In [ ]:
x = np.array(x)
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif["vif"] = [variance_inflation_factor(x,i) for i in range(x.shape[1])]
print(vif)
x = pd.DataFrame(x)

          vif
0    2.100373
1    2.844013
2   14.485758
3    1.152952
4   73.894947
5   77.948283
6   21.386850
7   14.699652
8   15.167725
9   61.227274
10  85.029547
11  20.104943
12  11.102025

In [ ]:
x.columns

RangeIndex(start=0, stop=13, step=1)

In [ ]:
durbin_watson(y)

np.float64(0.0752829340704826)

In [ ]:
# xtrain , xtest , ytrain , ytest = train_test_split(x,y,test_size = 0.2 , random_state = 1000)
xtrain , xtest , ytrain , ytest = train_test_split(x_vif,y,test_size = 0.2 , random_state = 1000)

In [ ]:
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(404, 3)
(102, 3)
(404,)
(102,)

In [ ]:

from sklearn import linear_model
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
# regr = LinearRegression()
regr = linear_model.LinearRegression()
# regr = DecisionTreeRegressor()
# regr = RandomForestRegressor()
# regr = GradientBoostingClassifier()

In [ ]:
regr.fit(xtrain , ytrain)

LinearRegression()

In [ ]:
regr.feature_importances_ # in linear model feature importances wont work cause linear model is not an embedded model

array([0.023985  , 0.00062491, 0.00349259, 0.00064185, 0.06217805,
       0.57793989, 0.00866408, 0.08201041, 0.00096601, 0.01332607,
       0.02165578, 0.02801587, 0.1764995 ])

In [ ]:
df1.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [ ]:
# ## Decision Tree cant use coefficient and intecept
# print("coefficients",regr.coef)
# print("intercept",regr.intercept)

In [ ]:
# test predict
y_pred = regr.predict(xtest)
y_pred

array([21.28721939, 17.23169201, 15.50074937, 39.40324074, 25.38255596,
       32.7359478 ,  9.17206841, 37.24330393, 18.05643006, 17.32398345,
       34.83311938, 20.94984853, 28.67618178, 13.59105484, 25.635163  ,
       24.05426189, 21.72643142, 13.17515619, 17.24475931, 30.52800124,
       23.87596583, 16.08368633, 33.07338415, 19.31279942, 19.13055834,
       13.20161493, 20.72158623, 17.48530444, 23.2681365 , 12.98218176,
       35.21320262, 30.88533238, 20.40082529, 24.64557593, 18.61478937,
       25.39486852, 25.03289866, 34.56747801, 27.82728449, 15.01888768,
       21.04593597, 37.02676683,  8.86246192, 22.46800861, 22.93903849,
       28.24245417, 26.7727513 , 17.54255681, 19.03295403, 24.33920351,
       23.48354875, 26.84361857, 15.64217399, 17.97463834, 29.34531385,
       18.79531642, 23.07067877, 12.63711587, 17.12150905, 17.36958789,
       15.72068021, 25.31760755, 27.77053501, 11.62690437, 29.25159282,
       31.49975724, 22.62620238, 22.06651894, 27.00486139, 19.55153006,
       21.64196721, 15.27852956, 25.87605976,  7.66937494, 19.67017186,
       31.08157692, 18.82055346, 16.11056029, 32.15879491, 20.59736721,
       24.33316405, 23.43109901, 20.4979526 , 30.43375567, 32.70657673,
        9.35845375, 21.66146849, 36.32821759, 15.90753658, 11.89739643,
       12.10358179, 24.50711332, 26.75386376, 13.78061612, 23.84274515,
       19.1877375 , 20.69290004, 27.44036774, 20.34930877, 18.15504585,
       19.73137426, 23.76599001])

In [ ]:
print(r2_score(ytest , y_pred))# coefficient and determination
print(mean_squared_error(ytest , y_pred))
# print(mean_absolute_error(ytest , y_pred))

0.30993838768644244
0.00031249868287013736

In [ ]:
y_pred_train = regr.predict(xtrain)
# y_pred_train

In [ ]:
print(r2_score(ytrain , y_pred_train))# coefficient and determination
print(mean_squared_error(ytrain , y_pred_train))
# print(mean_absolute_error(ytrain , y_pred_train)

0.7484272373846235
21.171852282225267

## Accuracy Improving **Technique**

In [ ]:
x_vif = df1.iloc[:,[0,1,3]]
x_vif

        crim    zn  chas
0    0.00632  18.0     0
1    0.02731   0.0     0
2    0.02729   0.0     0
3    0.03237   0.0     0
4    0.06905   0.0     0
..       ...   ...   ...
501  0.06263   0.0     0
502  0.04527   0.0     0
503  0.06076   0.0     0
504  0.10959   0.0     0
505  0.04741   0.0     0

[506 rows x 3 columns]

In [ ]:
bost_n = Normalizer().fit_transform(df1)
bost_n = pd.DataFrame(bost_n, columns = df1.columns)
bost_n

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.000013,0.035955,0.004614,0.0,0.001075,0.013134,0.130238,0.008170,0.001998,0.591265,0.030562,0.792814,0.009948,0.047940
1,0.000058,0.000000,0.014961,0.0,0.000992,0.013588,0.166966,0.010511,0.004232,0.512112,0.037668,0.839907,0.019342,0.045709
2,0.000058,0.000000,0.015133,0.0,0.001004,0.015379,0.130778,0.010632,0.004281,0.517974,0.038099,0.840809,0.008626,0.074272
3,0.000071,0.000000,0.004772,0.0,0.001003,0.015319,0.100257,0.013270,0.006567,0.485964,0.040935,0.863856,0.006436,0.073114
4,0.000150,0.000000,0.004740,0.0,0.000996,0.015539,0.117842,0.013181,0.006523,0.482675,0.040658,0.862945,0.011589,0.078707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.000129,0.000000,0.024652,0.0,0.001184,0.013624,0.142789,0.005122,0.002066,0.564130,0.043395,0.810012,0.019982,0.046288
502,0.000093,0.000000,0.024399,0.0,0.001172,0.012517,0.156866,0.004678,0.002045,0.558335,0.042949,0.811733,0.018570,0.042131
503,0.000124,0.000000,0.024272,0.0,0.001166,0.014193,0.185144,0.004410,0.002035,0.555433,0.042726,0.807514,0.011475,0.048626
504,0.000224,0.000000,0.024430,0.0,0.001173,0.013913,0.182867,0.004892,0.002048,0.559045,0.043003,0.805701,0.013270,0.045051
505,0.000097,0.000000,0.024382,0.0,0.001171,0.012324,0.165133,0.005120,0.002044,0.557936,0.042918,0.811152,0.016105,0.024320

In [ ]:
X = bost_n.drop("medv" , axis = 1)
Y = bost_n["medv"]

In [ ]:
bost_n.corr()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
crim,1.000000,-0.205217,0.245886,-0.063494,-0.080784,-0.493759,0.087648,-0.418596,0.614210,0.549562,-0.375030,-0.590271,0.251829,-0.452103
zn,-0.205217,1.000000,-0.521216,-0.019292,-0.297702,0.385258,-0.481557,0.643707,-0.313493,-0.329060,0.030620,0.296792,-0.374552,0.414241
indus,0.245886,-0.521216,1.000000,0.081398,0.415608,-0.449485,0.447608,-0.627394,0.282100,0.458148,-0.195065,-0.446802,0.480453,-0.469683
chas,-0.063494,-0.019292,0.081398,1.000000,0.146826,0.102897,0.114986,-0.052137,-0.039650,-0.075738,-0.017185,0.069623,-0.002320,0.150986
nox,-0.080784,-0.297702,0.415608,0.146826,1.000000,0.244445,0.600458,-0.260137,-0.210888,-0.117253,0.204856,0.038665,0.368345,0.074826
rm,-0.493759,0.385258,-0.449485,0.102897,0.244445,1.000000,-0.040462,0.579425,-0.700785,-0.798786,0.585528,0.678439,-0.380897,0.852346
age,0.087648,-0.481557,0.447608,0.114986,0.600458,-0.040462,1.000000,-0.493855,0.026088,0.081326,0.048708,-0.130955,0.497819,-0.158720
dis,-0.418596,0.643707,-0.627394,-0.052137,-0.260137,0.579425,-0.493855,1.000000,-0.561682,-0.616830,0.488374,0.578298,-0.325394,0.435835
rad,0.614210,-0.313493,0.282100,-0.039650,-0.210888,-0.700785,0.026088,-0.561682,1.000000,0.802895,-0.579262,-0.812752,0.168457,-0.544327
tax,0.549562,-0.329060,0.458148,-0.075738,-0.117253,-0.798786,0.081326,-0.616830,0.802895,1.000000,-0.649951,-0.939461,0.258608,-0.690844
ptratio,-0.375030,0.030620,-0.195065,-0.017185,0.204856,0.585528,0.048708,0.488374,-0.579262,-0.649951,1.000000,0.534471,0.046084,0.297022
black,-0.590271,0.296792,-0.446802,0.069623,0.038665,0.678439,-0.130955,0.578298,-0.812752,-0.939461,0.534471,1.000000,-0.295629,0.621367
lstat,0.251829,-0.374552,0.480453,-0.002320,0.368345,-0.380897,0.497819,-0.325394,0.168457,0.258608,0.046084,-0.295629,1.000000,-0.570873
medv,-0.452103,0.414241,-0.469683,0.150986,0.074826,0.852346,-0.158720,0.435835,-0.544327,-0.690844,0.297022,0.621367,-0.570873,1.000000

In [ ]:
Xtrain , Xtest , Ytrain , Ytest = train_test_split(X,Y,test_size = 0.2 , random_state = 1000)

In [ ]:
print(Xtrain.shape)
print(Xtest.shape)
print(Ytrain.shape)
print(Ytest.shape)

(404, 13)
(102, 13)
(404,)
(102,)

In [ ]:
regr.fit(Xtrain , Ytrain)

LinearRegression()

In [ ]:
# regr.feature_importances_

AttributeError: 'LinearRegression' object has no attribute 'feature_importances_'

In [ ]:
bost_n.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [ ]:
# test predict
y_pred1 = regr.predict(xtest)
y_pred1

array([-8.08071092e+00, -9.17464139e+00, -5.21898023e-01,  2.27852189e+01,
       -4.52460240e+00,  1.75742688e+01, -1.80411139e+01,  1.95125744e+01,
       -3.63822209e-03, -2.27328558e-01,  2.13213997e+01,  1.38741618e+00,
        1.11725004e+01, -9.18733201e+00,  3.20935083e+00,  8.66317588e+00,
        5.95802426e+00, -1.06245142e+01, -6.51687053e+00,  1.44417492e+01,
        1.03397040e+01, -3.41679025e+00,  1.48946859e+01, -5.42448358e+00,
       -1.04033648e+01, -3.91501682e+00,  6.44980265e-01, -1.16976452e+00,
       -6.13679997e+00, -5.38814506e+00,  2.29210222e+01,  9.74692056e+00,
       -7.04515444e+00,  8.82964397e+00, -7.01116887e+00,  6.38456555e+00,
        6.59807386e+00,  2.04068367e+01,  1.65382959e+01, -2.31655405e+00,
       -6.64672144e-01,  2.23800395e+01, -1.80724197e+01,  5.74189887e+00,
        4.04401952e+00,  9.63054946e+00,  1.34246392e+01, -8.86417579e+00,
       -7.36647643e+00,  6.94444300e+00,  5.89376808e+00,  5.26189559e+00,
       -5.18603176e+00, -8.13443933e+00,  8.71257660e+00,  2.64609697e+00,
        4.67186079e+00, -1.71799525e+01, -7.79861702e+00, -7.74608280e-01,
       -1.13562053e+01,  6.50303735e+00,  1.05287548e+01, -1.28749340e+01,
        1.01741611e+01,  1.32547132e+01, -4.76734639e+00, -4.21492776e+00,
        1.09308442e+01, -6.48569027e+00,  2.72833380e+00, -1.76958269e+00,
        3.91728369e+00, -1.81387748e+01, -4.77515635e-01,  1.39708795e+01,
        2.80918931e+00, -8.77107438e+00,  1.35553035e+01, -9.86715099e+00,
        6.82231864e+00,  4.04601350e+00,  1.09434453e+00,  1.62500447e+01,
        1.43169166e+01, -2.33438170e+01,  9.63021630e+00,  1.75212695e+01,
       -4.29905080e+00, -1.29296082e+01, -1.35378654e+01,  7.57596197e+00,
        9.50168401e+00, -1.38891671e+01,  7.87770618e+00,  1.33246605e+00,
        5.16241326e+00,  9.13120041e+00,  4.01736287e+00, -9.03195797e+00,
       -8.20683971e+00,  2.03786822e+00])

In [ ]:
# test predict
y_pred1 = regr.predict(Xtest)
y_pred1

array([0.02522539, 0.02195398, 0.03459968, 0.08339961, 0.02976166,
       0.07490908, 0.01301273, 0.07207177, 0.03560907, 0.03517199,
       0.08244352, 0.03810436, 0.0600562 , 0.02206949, 0.04108746,
       0.05447046, 0.04915729, 0.01985688, 0.02606235, 0.06540807,
       0.05910747, 0.02965928, 0.06647794, 0.02852925, 0.02146294,
       0.02673686, 0.03677119, 0.03324004, 0.02778728, 0.02519294,
       0.08722506, 0.05408366, 0.02663548, 0.05523601, 0.02669048,
       0.04826156, 0.04921246, 0.07773569, 0.06748355, 0.03094312,
       0.03442797, 0.08030921, 0.01256843, 0.04832345, 0.04356839,
       0.05458754, 0.0648008 , 0.0243213 , 0.02617291, 0.04967808,
       0.04798665, 0.04591485, 0.0268979 , 0.02525614, 0.05382666,
       0.0409859 , 0.0451918 , 0.01136555, 0.02489408, 0.03404613,
       0.01871606, 0.04729907, 0.0569582 , 0.01853475, 0.05669915,
       0.06225848, 0.02952066, 0.02942691, 0.05899655, 0.02735578,
       0.04094006, 0.03214781, 0.04378174, 0.00919566, 0.03482414,
       0.06611288, 0.04118545, 0.02277028, 0.0625153 , 0.02253042,
       0.04969864, 0.04357572, 0.03778069, 0.07040435, 0.06350153,
       0.0053316 , 0.0567894 , 0.0690504 , 0.02830353, 0.01758732,
       0.01836526, 0.05099614, 0.05549529, 0.01790871, 0.05174019,
       0.0382139 , 0.04685809, 0.05385476, 0.04429822, 0.02356957,
       0.02510304, 0.03908605])

In [ ]:
print(r2_score(Ytest , y_pred1))# coefficient and determination
print(mean_squared_error(Ytest , y_pred1))
# print(mean_absolute_error(ytest , y_pred))

0.8648669514123365
6.119583953422802e-05

In [ ]:
y_pred_train = regr.predict(Xtrain)
# y_pred_train

In [ ]:
print(r2_score(Ytrain , y_pred_train))# coefficient and determination
print(mean_squared_error(Ytrain , y_pred_train))
# print(mean_absolute_error(ytrain , y_pred_train)

1.0
0.0